# Generated by Django 6.0 on 2025-12-11 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_gamepost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
