# Generated by Django 6.0 on 2025-12-12 01:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_gamepost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
